CREATE SEQUENCE IF NOT EXISTS bank.accounts_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS bank.transactions_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS bank.clients_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS bank.roles_seq START WITH 1 INCREMENT BY 50;